env:
  - CGO_ENABLED=1
builds:
  - id: suave-playground-darwin-amd64
    binary: suave-playground
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -trimpath
  - id: suave-playground-darwin-arm64
    binary: suave-playground
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -trimpath
  - id: suave-playground-linux-amd64
    binary: suave-playground
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-Wl,-z,stack-size=0x800000 --static"
    tags:
      - netgo
      - osusergo
  - id: suave-playground-linux-arm64
    binary: suave-playground
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-Wl,-z,stack-size=0x800000 --static"
    tags:
      - netgo
      - osusergo

archives:
  - id: w/version
    builds:
      - suave-playground-darwin-amd64
      - suave-playground-darwin-arm64
      - suave-playground-linux-amd64
      - suave-playground-linux-arm64
    name_template: "suave-playground_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    format: zip
    files:
      - none*

checksum:
  name_template: "checksums.txt"

release:
  draft: true
