CONFIG_NAME: mainnet
PRESET_BASE: mainnet
TERMINAL_TOTAL_DIFFICULTY: "0"
TERMINAL_BLOCK_HASH: "0x0000000000000000000000000000000000000000000000000000000000000000"
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615
SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY: 128
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 80
MIN_GENESIS_TIME: 1720099319
GENESIS_FORK_VERSION: "0x42424242"
GENESIS_DELAY: 0
ALTAIR_FORK_VERSION: "0x01000000"
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: "0x02000000"
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: "0x03000000"
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_VERSION: "0x04000000"
DENEB_FORK_EPOCH: 0
SECONDS_PER_SLOT: 3
SECONDS_PER_ETH1_BLOCK: 3
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 256
ETH1_FOLLOW_DISTANCE: 128
SUBNETS_PER_NODE: 2
INACTIVITY_SCORE_BIAS: 4
INACTIVITY_SCORE_RECOVERY_RATE: 16
EJECTION_BALANCE: 16000000000
MIN_PER_EPOCH_CHURN_LIMIT: 4
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: 8
CHURN_LIMIT_QUOTIENT: 65536
PROPOSER_SCORE_BOOST: 40
DEPOSIT_CHAIN_ID: 4242
DEPOSIT_NETWORK_ID: 4242
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
GOSSIP_MAX_SIZE: 10485760
MAX_REQUEST_BLOCKS: 1024
EPOCHS_PER_SUBNET_SUBSCRIPTION: 256
MIN_EPOCHS_FOR_BLOCK_REQUESTS: 33024
MAX_CHUNK_SIZE: 10485760
TTFB_TIMEOUT: 5
RESP_TIMEOUT: 10
ATTESTATION_PROPAGATION_SLOT_RANGE: 32
MAXIMUM_GOSSIP_CLOCK_DISPARITY_MILLIS: 500
MESSAGE_DOMAIN_INVALID_SNAPPY: "0x00000000"
MESSAGE_DOMAIN_VALID_SNAPPY: "0x01000000"
ATTESTATION_SUBNET_EXTRA_BITS: 0
ATTESTATION_SUBNET_PREFIX_BITS: 6
MAX_REQUEST_BLOCKS_DENEB: 128
MAX_REQUEST_BLOB_SIDECARS: 768
MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 4096
BLOB_SIDECAR_SUBNET_COUNT: 6
