name: Checks

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Download artifacts
        run: go run main.go download-artifacts

      - name: Run playground
        run: go run main.go --output /tmp/playground &

      - name: Validate that blocks are created
        run: go run main.go validate

      - name: Archive playground logs
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: playground-logs
          path: /tmp/playground/logs
          retention-days: 5
