name: Checks

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [warp-ubuntu-latest-x64-16x, macos-14]
    runs-on: ${{ matrix.os }}
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run playground
        run: go run main.go &
      
      - name: Validate that blocks are created
        run: go run main.go validate
